USE FCC_ULS_ImportDB  
GO

--dbo.PUBACC_APP_A2
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_A2_unique_system_identifier ON dbo.PUBACC_APP_A2 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_A2_uls_file_number ON dbo.PUBACC_APP_A2 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_A3
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_A3_unique_system_identifier ON dbo.PUBACC_APP_A3 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_A3_uls_file_number ON dbo.PUBACC_APP_A3 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AC_unique_system_identifier ON dbo.PUBACC_APP_AC 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AC_uls_file_number ON dbo.PUBACC_APP_AC 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AD
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AD_unique_system_identifier ON dbo.PUBACC_APP_AD 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AD_uls_file_number ON dbo.PUBACC_APP_AD 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AG
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AG_unique_system_identifier ON dbo.PUBACC_APP_AG 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AG_uls_file_number ON dbo.PUBACC_APP_AG 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AH
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AH_unique_system_identifier ON dbo.PUBACC_APP_AH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AH_uls_file_number ON dbo.PUBACC_APP_AH
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AM
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AM_unique_system_identifier ON dbo.PUBACC_APP_AM
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AM_uls_file_number ON dbo.PUBACC_APP_AM
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AN
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AN_unique_system_identifier ON dbo.PUBACC_APP_AN
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AN_uls_file_number ON dbo.PUBACC_APP_AN
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AP
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AP_unique_system_identifier ON dbo.PUBACC_APP_AP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AP_uls_file_number ON dbo.PUBACC_APP_AP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AS
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AS_unique_system_identifier ON dbo.PUBACC_APP_AS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AS_uls_file_number ON dbo.PUBACC_APP_AS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_AT
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AT_unique_system_identifier ON dbo.PUBACC_APP_AT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_AT_uls_file_number ON dbo.PUBACC_APP_AT
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BC_unique_system_identifier ON dbo.PUBACC_APP_BC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BC_uls_file_number ON dbo.PUBACC_APP_BC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BD
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BD_unique_system_identifier ON dbo.PUBACC_APP_BD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BD_uls_file_number ON dbo.PUBACC_APP_BD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BE
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BE_unique_system_identifier ON dbo.PUBACC_APP_BE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BE_uls_file_number ON dbo.PUBACC_APP_BE
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BF
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BF_unique_system_identifier ON dbo.PUBACC_APP_BF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BL
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BL_unique_system_identifier ON dbo.PUBACC_APP_BL
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BO
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BO_unique_system_identifier ON dbo.PUBACC_APP_BO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_BT
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BT_unique_system_identifier ON dbo.PUBACC_APP_BT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_BT_uls_file_number ON dbo.PUBACC_APP_BT
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_CD
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CD_unique_system_identifier ON dbo.PUBACC_APP_CD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CD_uls_file_number ON dbo.PUBACC_APP_CD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_CF
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CF_unique_system_identifier ON dbo.PUBACC_APP_CF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CF_uls_file_number ON dbo.PUBACC_APP_CF
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CF_Assign_Callsign ON dbo.PUBACC_APP_CF
(
	[Assign_Callsign] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_CG
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CG_unique_system_identifier ON dbo.PUBACC_APP_CG
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CG_uls_file_number ON dbo.PUBACC_APP_CG
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_CO
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CO_unique_system_identifier ON dbo.PUBACC_APP_CO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CO_uls_file_number ON dbo.PUBACC_APP_CO
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_CP
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CP_unique_system_identifier ON dbo.PUBACC_APP_CP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CP_uls_file_number ON dbo.PUBACC_APP_CP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_CS
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CS_unique_system_identifier ON dbo.PUBACC_APP_CS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_CS_uls_file_number ON dbo.PUBACC_APP_CS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_EM
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EM_unique_system_identifier ON dbo.PUBACC_APP_EM 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EM_uls_file_number ON dbo.PUBACC_APP_EM 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EM_call_sign ON dbo.PUBACC_APP_EM 
(
	[call_sign] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_EN
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_unique_system_identifier ON dbo.PUBACC_APP_EN 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_uls_file_number ON dbo.PUBACC_APP_EN 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_call_sign ON dbo.PUBACC_APP_EN 
(
	[call_sign] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_entity_name ON dbo.PUBACC_APP_EN 
(
	[entity_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_first_name ON dbo.PUBACC_APP_EN 
(
	[first_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_last_name ON dbo.PUBACC_APP_EN 
(
	[last_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_EN_city ON dbo.PUBACC_APP_EN 
(
	[city] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_F2
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F2_unique_system_identifier ON dbo.PUBACC_APP_F2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F2_uls_file_number ON dbo.PUBACC_APP_F2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_F3
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F3_unique_system_identifier ON dbo.PUBACC_APP_F3
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F3_uls_file_number ON dbo.PUBACC_APP_F3
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_F4
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F4_unique_system_identifier ON dbo.PUBACC_APP_F4
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F4_uls_file_number ON dbo.PUBACC_APP_F4
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_F5
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F5_unique_system_identifier ON dbo.PUBACC_APP_F5
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_F6
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F6_unique_system_identifier ON dbo.PUBACC_APP_F6
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_F6_uls_file_number ON dbo.PUBACC_APP_F6
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_FA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FA_unique_system_identifier ON dbo.PUBACC_APP_FA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FA_uls_file_number ON dbo.PUBACC_APP_FA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_FC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FC_unique_system_identifier ON dbo.PUBACC_APP_FC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FC_uls_file_number ON dbo.PUBACC_APP_FC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_FF
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FF_unique_system_identifier ON dbo.PUBACC_APP_FF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_FR
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FR_unique_system_identifier ON dbo.PUBACC_APP_FR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FR_uls_file_number ON dbo.PUBACC_APP_FR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_FS
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FS_unique_system_identifier ON dbo.PUBACC_APP_FS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_FT
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FT_unique_system_identifier ON dbo.PUBACC_APP_FT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_FT_uls_file_number ON dbo.PUBACC_APP_FT
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_HD
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_HD_unique_system_identifier ON dbo.PUBACC_APP_HD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_HD_uls_file_number ON dbo.PUBACC_APP_HD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_HS
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_HS_unique_system_identifier ON dbo.PUBACC_APP_HS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_HS_uls_file_number ON dbo.PUBACC_APP_HS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_IA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_IA_unique_system_identifier ON dbo.PUBACC_APP_IA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_IA_uls_file_number ON dbo.PUBACC_APP_IA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_IR
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_IR_unique_system_identifier ON dbo.PUBACC_APP_IR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_IR_uls_file_number ON dbo.PUBACC_APP_IR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_L2
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L2_unique_system_identifier ON dbo.PUBACC_APP_L2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L2_uls_file_number ON dbo.PUBACC_APP_L2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_L3
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L3_unique_system_identifier ON dbo.PUBACC_APP_L3
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L3_uls_file_number ON dbo.PUBACC_APP_L3
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_L4
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L4_unique_system_identifier ON dbo.PUBACC_APP_L4
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L4_uls_file_number ON dbo.PUBACC_APP_L4
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_L5
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L5_unique_system_identifier ON dbo.PUBACC_APP_L5
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L5_uls_file_number ON dbo.PUBACC_APP_L5
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_L6
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L6_unique_system_identifier ON dbo.PUBACC_APP_L6
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_L6_uls_file_number ON dbo.PUBACC_APP_L6
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LA_unique_system_identifier ON dbo.PUBACC_APP_LA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LC_unique_system_identifier ON dbo.PUBACC_APP_LC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LC_uls_file_number ON dbo.PUBACC_APP_LC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LD
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LD_unique_system_identifier ON dbo.PUBACC_APP_LD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LD_uls_file_number ON dbo.PUBACC_APP_LD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LF
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LF_unique_system_identifier ON dbo.PUBACC_APP_LF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LH
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LH_unique_system_identifier ON dbo.PUBACC_APP_LH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LL
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LL_unique_system_identifier ON dbo.PUBACC_APP_LL
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LL_uls_file_number ON dbo.PUBACC_APP_LL
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LM
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LM_unique_system_identifier ON dbo.PUBACC_APP_LM
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LM_uls_file_number ON dbo.PUBACC_APP_LM
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LO
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LO_unique_system_identifier ON dbo.PUBACC_APP_LO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LO_uls_file_number ON dbo.PUBACC_APP_LO
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_LS
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_LS_unique_system_identifier ON dbo.PUBACC_APP_LS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MC_unique_system_identifier ON dbo.PUBACC_APP_MC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MC_uls_file_number ON dbo.PUBACC_APP_MC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_ME
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_ME_unique_system_identifier ON dbo.PUBACC_APP_ME
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_ME_uls_file_number ON dbo.PUBACC_APP_ME
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MF
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MF_unique_system_identifier ON dbo.PUBACC_APP_MF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MF_uls_file_number ON dbo.PUBACC_APP_MF
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MH
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MH_unique_system_identifier ON dbo.PUBACC_APP_MH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MH_uls_file_number ON dbo.PUBACC_APP_MH
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MI
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MI_unique_system_identifier ON dbo.PUBACC_APP_MI
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MI_uls_file_number ON dbo.PUBACC_APP_MI
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MK
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MK_unique_system_identifier ON dbo.PUBACC_APP_MK
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MK_uls_file_number ON dbo.PUBACC_APP_MK
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MP
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MP_unique_system_identifier ON dbo.PUBACC_APP_MP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MP_uls_file_number ON dbo.PUBACC_APP_MP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_MW
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MW_unique_system_identifier ON dbo.PUBACC_APP_MW
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_MW_uls_file_number ON dbo.PUBACC_APP_MW
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_O2
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_O2_unique_system_identifier ON dbo.PUBACC_APP_O2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_O2_uls_file_number ON dbo.PUBACC_APP_O2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_OP
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_OP_unique_system_identifier ON dbo.PUBACC_APP_OP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_OP_uls_file_number ON dbo.PUBACC_APP_OP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_P2
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_P2_unique_system_identifier ON dbo.PUBACC_APP_P2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_P2_uls_file_number ON dbo.PUBACC_APP_P2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_PA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_PA_unique_system_identifier ON dbo.PUBACC_APP_PA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_PA_uls_file_number ON dbo.PUBACC_APP_PA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_PC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_PC_unique_system_identifier ON dbo.PUBACC_APP_PC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_PC_uls_file_number ON dbo.PUBACC_APP_PC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_RA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RA_unique_system_identifier ON dbo.PUBACC_APP_RA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RA_uls_file_number ON dbo.PUBACC_APP_RA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_RC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RC_unique_system_identifier ON dbo.PUBACC_APP_RC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RC_uls_file_number ON dbo.PUBACC_APP_RC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_RE
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RE_unique_system_identifier ON dbo.PUBACC_APP_RE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RE_uls_file_number ON dbo.PUBACC_APP_RE
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_RI
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RI_unique_system_identifier ON dbo.PUBACC_APP_RI
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RI_uls_file_number ON dbo.PUBACC_APP_RI
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_RZ
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RZ_unique_system_identifier ON dbo.PUBACC_APP_RZ
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_RZ_uls_file_number ON dbo.PUBACC_APP_RZ
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SC_unique_system_identifier ON dbo.PUBACC_APP_SC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SC_uls_file_number ON dbo.PUBACC_APP_SC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SE
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SE_unique_system_identifier ON dbo.PUBACC_APP_SE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SE_uls_file_number ON dbo.PUBACC_APP_SE
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SF
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SF_unique_system_identifier ON dbo.PUBACC_APP_SF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SF_uls_file_number ON dbo.PUBACC_APP_SF
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SG
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SG_unique_system_identifier ON dbo.PUBACC_APP_SG
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SG_uls_file_number ON dbo.PUBACC_APP_SG
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SH
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SH_unique_system_identifier ON dbo.PUBACC_APP_SH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SH_uls_file_number ON dbo.PUBACC_APP_SH
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SI
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SI_unique_system_identifier ON dbo.PUBACC_APP_SI
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SI_uls_file_number ON dbo.PUBACC_APP_SI
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SR
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SR_unique_system_identifier ON dbo.PUBACC_APP_SR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SR_uls_file_number ON dbo.PUBACC_APP_SR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_SV
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SV_unique_system_identifier ON dbo.PUBACC_APP_SV
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_SV_uls_file_number ON dbo.PUBACC_APP_SV
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_TA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_TA_unique_system_identifier ON dbo.PUBACC_APP_TA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_TA_uls_file_number ON dbo.PUBACC_APP_TA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_TL
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_TL_unique_system_identifier ON dbo.PUBACC_APP_TL
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_TL_uls_file_number ON dbo.PUBACC_APP_TL
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_TP
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_TP_unique_system_identifier ON dbo.PUBACC_APP_TP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_TP_uls_file_number ON dbo.PUBACC_APP_TP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_UA
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_UA_unique_system_identifier ON dbo.PUBACC_APP_UA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_UA_uls_file_number ON dbo.PUBACC_APP_UA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_APP_VC
CREATE NONCLUSTERED INDEX IX_PUBACC_APP_VC_unique_system_identifier ON dbo.PUBACC_APP_VC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_APP_VC_uls_file_number ON dbo.PUBACC_APP_VC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_AT
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_AT_unique_system_identifier ON dbo.TOWER_PUBACC_APP_AT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_CO
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_CO_unique_system_identifier ON dbo.TOWER_PUBACC_APP_CO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_DE
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_DE_faa_study_number ON dbo.TOWER_PUBACC_APP_DE
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_DP
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_DP_faa_study_number ON dbo.TOWER_PUBACC_APP_DP
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_DR
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_DR_faa_study_number ON dbo.TOWER_PUBACC_APP_DR
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_EN
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_EN_unique_system_identifier ON dbo.TOWER_PUBACC_APP_EN
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_HS
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_HS_unique_system_identifier ON dbo.TOWER_PUBACC_APP_HS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_RA
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_RA_unique_system_identifier ON dbo.TOWER_PUBACC_APP_RA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_RA_faa_study_number ON dbo.TOWER_PUBACC_APP_RA
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_RE
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_RE_unique_system_identifier ON dbo.TOWER_PUBACC_APP_RE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_RS
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_RS_unique_system_identifier ON dbo.TOWER_PUBACC_APP_RS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_APP_SC
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_APP_SC_unique_system_identifier ON dbo.TOWER_PUBACC_APP_SC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

use tempdb
GO
