USE FCC_ULS_ImportDB  
GO

--dbo.OWNER_PUBACC_A
CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_A_file_num ON dbo.OWNER_PUBACC_A 
(
	[file_num] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_A_unique_system_identifier ON dbo.OWNER_PUBACC_A 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.OWNER_PUBACC_D
CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_D_file_num ON dbo.OWNER_PUBACC_D 
(
	[file_num] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_D_unique_system_identifier ON dbo.OWNER_PUBACC_D 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.OWNER_PUBACC_F
CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_F_file_num ON dbo.OWNER_PUBACC_F 
(
	[file_num] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_F_unique_system_identifier ON dbo.OWNER_PUBACC_F 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.OWNER_PUBACC_H
CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_H_file_num ON dbo.OWNER_PUBACC_H 
(
	[file_num] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_H_unique_system_identifier ON dbo.OWNER_PUBACC_H 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.OWNER_PUBACC_O
CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_O_file_num ON dbo.OWNER_PUBACC_O 
(
	[file_num] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_O_unique_system_identifier ON dbo.OWNER_PUBACC_O 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.OWNER_PUBACC_T
CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_T_file_num ON dbo.OWNER_PUBACC_T 
(
	[file_num] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_OWNER_PUBACC_T_unique_system_identifier ON dbo.OWNER_PUBACC_T 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_A2
CREATE NONCLUSTERED INDEX IX_PUBACC_A2_unique_system_identifier ON dbo.PUBACC_A2 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_A2_uls_file_number ON dbo.PUBACC_A2 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_A3
CREATE NONCLUSTERED INDEX IX_PUBACC_A3_unique_system_identifier ON dbo.PUBACC_A3 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_A3_uls_file_number ON dbo.PUBACC_A3 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AC
CREATE NONCLUSTERED INDEX IX_PUBACC_AC_unique_system_identifier ON dbo.PUBACC_AC 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AC_uls_file_number ON dbo.PUBACC_AC 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AD
CREATE NONCLUSTERED INDEX IX_PUBACC_AD_unique_system_identifier ON dbo.PUBACC_AD 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AD_uls_file_number ON dbo.PUBACC_AD 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AG
CREATE NONCLUSTERED INDEX IX_PUBACC_AG_unique_system_identifier ON dbo.PUBACC_AG 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AG_uls_file_number ON dbo.PUBACC_AG 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AH
CREATE NONCLUSTERED INDEX IX_PUBACC_AH_unique_system_identifier ON dbo.PUBACC_AH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AH_uls_file_number ON dbo.PUBACC_AH
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AM
CREATE NONCLUSTERED INDEX IX_PUBACC_AM_unique_system_identifier ON dbo.PUBACC_AM
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AM_uls_file_number ON dbo.PUBACC_AM
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AN
CREATE NONCLUSTERED INDEX IX_PUBACC_AN_unique_system_identifier ON dbo.PUBACC_AN
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AN_uls_file_number ON dbo.PUBACC_AN
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AP
CREATE NONCLUSTERED INDEX IX_PUBACC_AP_unique_system_identifier ON dbo.PUBACC_AP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AP_uls_file_number ON dbo.PUBACC_AP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AS
CREATE NONCLUSTERED INDEX IX_PUBACC_AS_unique_system_identifier ON dbo.PUBACC_AS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AS_uls_file_number ON dbo.PUBACC_AS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_AT
CREATE NONCLUSTERED INDEX IX_PUBACC_AT_unique_system_identifier ON dbo.PUBACC_AT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_AT_uls_file_number ON dbo.PUBACC_AT
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BC
CREATE NONCLUSTERED INDEX IX_PUBACC_BC_unique_system_identifier ON dbo.PUBACC_BC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_BC_uls_file_number ON dbo.PUBACC_BC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BD
CREATE NONCLUSTERED INDEX IX_PUBACC_BD_unique_system_identifier ON dbo.PUBACC_BD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_BD_uls_file_number ON dbo.PUBACC_BD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BE
CREATE NONCLUSTERED INDEX IX_PUBACC_BE_unique_system_identifier ON dbo.PUBACC_BE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_BE_uls_file_number ON dbo.PUBACC_BE
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BF
CREATE NONCLUSTERED INDEX IX_PUBACC_BF_unique_system_identifier ON dbo.PUBACC_BF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BL
CREATE NONCLUSTERED INDEX IX_PUBACC_BL_unique_system_identifier ON dbo.PUBACC_BL
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BO
CREATE NONCLUSTERED INDEX IX_PUBACC_BO_unique_system_identifier ON dbo.PUBACC_BO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_BT
CREATE NONCLUSTERED INDEX IX_PUBACC_BT_unique_system_identifier ON dbo.PUBACC_BT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_BT_uls_file_number ON dbo.PUBACC_BT
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_CD
CREATE NONCLUSTERED INDEX IX_PUBACC_CD_unique_system_identifier ON dbo.PUBACC_CD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CD_uls_file_number ON dbo.PUBACC_CD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_CF
CREATE NONCLUSTERED INDEX IX_PUBACC_CF_unique_system_identifier ON dbo.PUBACC_CF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CF_uls_file_number ON dbo.PUBACC_CF
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CF_Assign_Callsign ON dbo.PUBACC_CF
(
	[Assign_Callsign] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_CG
CREATE NONCLUSTERED INDEX IX_PUBACC_CG_unique_system_identifier ON dbo.PUBACC_CG
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CG_uls_file_number ON dbo.PUBACC_CG
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_CO
CREATE NONCLUSTERED INDEX IX_PUBACC_CO_unique_system_identifier ON dbo.PUBACC_CO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CO_uls_file_number ON dbo.PUBACC_CO
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_CP
CREATE NONCLUSTERED INDEX IX_PUBACC_CP_unique_system_identifier ON dbo.PUBACC_CP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CP_uls_file_number ON dbo.PUBACC_CP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_CS
CREATE NONCLUSTERED INDEX IX_PUBACC_CS_unique_system_identifier ON dbo.PUBACC_CS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_CS_uls_file_number ON dbo.PUBACC_CS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_EM
CREATE NONCLUSTERED INDEX IX_PUBACC_EM_unique_system_identifier ON dbo.PUBACC_EM 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EM_uls_file_number ON dbo.PUBACC_EM 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EM_call_sign ON dbo.PUBACC_EM 
(
	[call_sign] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_EN
CREATE NONCLUSTERED INDEX IX_PUBACC_EN_unique_system_identifier ON dbo.PUBACC_EN 
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EN_uls_file_number ON dbo.PUBACC_EN 
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EN_call_sign ON dbo.PUBACC_EN 
(
	[call_sign] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EN_entity_name ON dbo.PUBACC_EN 
(
	[entity_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EN_first_name ON dbo.PUBACC_EN 
(
	[first_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EN_last_name ON dbo.PUBACC_EN 
(
	[last_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_EN_city ON dbo.PUBACC_EN 
(
	[city] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_F2
CREATE NONCLUSTERED INDEX IX_PUBACC_F2_unique_system_identifier ON dbo.PUBACC_F2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_F2_uls_file_number ON dbo.PUBACC_F2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_F3
CREATE NONCLUSTERED INDEX IX_PUBACC_F3_unique_system_identifier ON dbo.PUBACC_F3
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_F3_uls_file_number ON dbo.PUBACC_F3
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_F4
CREATE NONCLUSTERED INDEX IX_PUBACC_F4_unique_system_identifier ON dbo.PUBACC_F4
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_F4_uls_file_number ON dbo.PUBACC_F4
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_F5
CREATE NONCLUSTERED INDEX IX_PUBACC_F5_unique_system_identifier ON dbo.PUBACC_F5
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_F6
CREATE NONCLUSTERED INDEX IX_PUBACC_F6_unique_system_identifier ON dbo.PUBACC_F6
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_F6_uls_file_number ON dbo.PUBACC_F6
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_FA
CREATE NONCLUSTERED INDEX IX_PUBACC_FA_unique_system_identifier ON dbo.PUBACC_FA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_FA_uls_file_number ON dbo.PUBACC_FA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_FC
CREATE NONCLUSTERED INDEX IX_PUBACC_FC_unique_system_identifier ON dbo.PUBACC_FC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_FC_uls_file_number ON dbo.PUBACC_FC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_FF
CREATE NONCLUSTERED INDEX IX_PUBACC_FF_unique_system_identifier ON dbo.PUBACC_FF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_FR
CREATE NONCLUSTERED INDEX IX_PUBACC_FR_unique_system_identifier ON dbo.PUBACC_FR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_FR_uls_file_number ON dbo.PUBACC_FR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_FS
CREATE NONCLUSTERED INDEX IX_PUBACC_FS_unique_system_identifier ON dbo.PUBACC_FS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_FT
CREATE NONCLUSTERED INDEX IX_PUBACC_FT_unique_system_identifier ON dbo.PUBACC_FT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_FT_uls_file_number ON dbo.PUBACC_FT
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_HD
CREATE NONCLUSTERED INDEX IX_PUBACC_HD_unique_system_identifier ON dbo.PUBACC_HD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_HD_uls_file_number ON dbo.PUBACC_HD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_HS
CREATE NONCLUSTERED INDEX IX_PUBACC_HS_unique_system_identifier ON dbo.PUBACC_HS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_HS_uls_file_number ON dbo.PUBACC_HS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_IA
CREATE NONCLUSTERED INDEX IX_PUBACC_IA_unique_system_identifier ON dbo.PUBACC_IA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_IA_uls_file_number ON dbo.PUBACC_IA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_IR
CREATE NONCLUSTERED INDEX IX_PUBACC_IR_unique_system_identifier ON dbo.PUBACC_IR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_IR_uls_file_number ON dbo.PUBACC_IR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_L2
CREATE NONCLUSTERED INDEX IX_PUBACC_L2_unique_system_identifier ON dbo.PUBACC_L2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_L2_uls_file_number ON dbo.PUBACC_L2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_L3
CREATE NONCLUSTERED INDEX IX_PUBACC_L3_unique_system_identifier ON dbo.PUBACC_L3
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_L3_uls_file_number ON dbo.PUBACC_L3
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_L4
CREATE NONCLUSTERED INDEX IX_PUBACC_L4_unique_system_identifier ON dbo.PUBACC_L4
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_L4_uls_file_number ON dbo.PUBACC_L4
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_L5
CREATE NONCLUSTERED INDEX IX_PUBACC_L5_unique_system_identifier ON dbo.PUBACC_L5
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_L5_uls_file_number ON dbo.PUBACC_L5
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_L6
CREATE NONCLUSTERED INDEX IX_PUBACC_L6_unique_system_identifier ON dbo.PUBACC_L6
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_L6_uls_file_number ON dbo.PUBACC_L6
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LA
CREATE NONCLUSTERED INDEX IX_PUBACC_LA_unique_system_identifier ON dbo.PUBACC_LA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LC
CREATE NONCLUSTERED INDEX IX_PUBACC_LC_unique_system_identifier ON dbo.PUBACC_LC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_LC_uls_file_number ON dbo.PUBACC_LC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LD
CREATE NONCLUSTERED INDEX IX_PUBACC_LD_unique_system_identifier ON dbo.PUBACC_LD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_LD_uls_file_number ON dbo.PUBACC_LD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LF
CREATE NONCLUSTERED INDEX IX_PUBACC_LF_unique_system_identifier ON dbo.PUBACC_LF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LH
CREATE NONCLUSTERED INDEX IX_PUBACC_LH_unique_system_identifier ON dbo.PUBACC_LH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LL
CREATE NONCLUSTERED INDEX IX_PUBACC_LL_unique_system_identifier ON dbo.PUBACC_LL
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_LL_uls_file_number ON dbo.PUBACC_LL
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LM
CREATE NONCLUSTERED INDEX IX_PUBACC_LM_unique_system_identifier ON dbo.PUBACC_LM
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_LM_uls_file_number ON dbo.PUBACC_LM
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LO
CREATE NONCLUSTERED INDEX IX_PUBACC_LO_unique_system_identifier ON dbo.PUBACC_LO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_LO_uls_file_number ON dbo.PUBACC_LO
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_LS
CREATE NONCLUSTERED INDEX IX_PUBACC_LS_unique_system_identifier ON dbo.PUBACC_LS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MC
CREATE NONCLUSTERED INDEX IX_PUBACC_MC_unique_system_identifier ON dbo.PUBACC_MC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MC_uls_file_number ON dbo.PUBACC_MC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_ME
CREATE NONCLUSTERED INDEX IX_PUBACC_ME_unique_system_identifier ON dbo.PUBACC_ME
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_ME_uls_file_number ON dbo.PUBACC_ME
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MF
CREATE NONCLUSTERED INDEX IX_PUBACC_MF_unique_system_identifier ON dbo.PUBACC_MF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MF_uls_file_number ON dbo.PUBACC_MF
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MH
CREATE NONCLUSTERED INDEX IX_PUBACC_MH_unique_system_identifier ON dbo.PUBACC_MH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MH_uls_file_number ON dbo.PUBACC_MH
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MI
CREATE NONCLUSTERED INDEX IX_PUBACC_MI_unique_system_identifier ON dbo.PUBACC_MI
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MI_uls_file_number ON dbo.PUBACC_MI
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MK
CREATE NONCLUSTERED INDEX IX_PUBACC_MK_unique_system_identifier ON dbo.PUBACC_MK
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MK_uls_file_number ON dbo.PUBACC_MK
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MP
CREATE NONCLUSTERED INDEX IX_PUBACC_MP_unique_system_identifier ON dbo.PUBACC_MP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MP_uls_file_number ON dbo.PUBACC_MP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_MW
CREATE NONCLUSTERED INDEX IX_PUBACC_MW_unique_system_identifier ON dbo.PUBACC_MW
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_MW_uls_file_number ON dbo.PUBACC_MW
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_O2
CREATE NONCLUSTERED INDEX IX_PUBACC_O2_unique_system_identifier ON dbo.PUBACC_O2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_O2_uls_file_number ON dbo.PUBACC_O2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_OP
CREATE NONCLUSTERED INDEX IX_PUBACC_OP_unique_system_identifier ON dbo.PUBACC_OP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_OP_uls_file_number ON dbo.PUBACC_OP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_P2
CREATE NONCLUSTERED INDEX IX_PUBACC_P2_unique_system_identifier ON dbo.PUBACC_P2
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_P2_uls_file_number ON dbo.PUBACC_P2
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_PA
CREATE NONCLUSTERED INDEX IX_PUBACC_PA_unique_system_identifier ON dbo.PUBACC_PA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_PA_uls_file_number ON dbo.PUBACC_PA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_PC
CREATE NONCLUSTERED INDEX IX_PUBACC_PC_unique_system_identifier ON dbo.PUBACC_PC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_PC_uls_file_number ON dbo.PUBACC_PC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_RA
CREATE NONCLUSTERED INDEX IX_PUBACC_RA_unique_system_identifier ON dbo.PUBACC_RA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_RA_uls_file_number ON dbo.PUBACC_RA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_RC
CREATE NONCLUSTERED INDEX IX_PUBACC_RC_unique_system_identifier ON dbo.PUBACC_RC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_RC_uls_file_number ON dbo.PUBACC_RC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_RE
CREATE NONCLUSTERED INDEX IX_PUBACC_RE_unique_system_identifier ON dbo.PUBACC_RE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_RE_uls_file_number ON dbo.PUBACC_RE
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_RI
CREATE NONCLUSTERED INDEX IX_PUBACC_RI_unique_system_identifier ON dbo.PUBACC_RI
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_RI_uls_file_number ON dbo.PUBACC_RI
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_RZ
CREATE NONCLUSTERED INDEX IX_PUBACC_RZ_unique_system_identifier ON dbo.PUBACC_RZ
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_RZ_uls_file_number ON dbo.PUBACC_RZ
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SC
CREATE NONCLUSTERED INDEX IX_PUBACC_SC_unique_system_identifier ON dbo.PUBACC_SC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SC_uls_file_number ON dbo.PUBACC_SC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SE
CREATE NONCLUSTERED INDEX IX_PUBACC_SE_unique_system_identifier ON dbo.PUBACC_SE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SE_uls_file_number ON dbo.PUBACC_SE
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SF
CREATE NONCLUSTERED INDEX IX_PUBACC_SF_unique_system_identifier ON dbo.PUBACC_SF
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SF_uls_file_number ON dbo.PUBACC_SF
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SG
CREATE NONCLUSTERED INDEX IX_PUBACC_SG_unique_system_identifier ON dbo.PUBACC_SG
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SG_uls_file_number ON dbo.PUBACC_SG
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SH
CREATE NONCLUSTERED INDEX IX_PUBACC_SH_unique_system_identifier ON dbo.PUBACC_SH
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SH_uls_file_number ON dbo.PUBACC_SH
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SI
CREATE NONCLUSTERED INDEX IX_PUBACC_SI_unique_system_identifier ON dbo.PUBACC_SI
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SI_uls_file_number ON dbo.PUBACC_SI
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SR
CREATE NONCLUSTERED INDEX IX_PUBACC_SR_unique_system_identifier ON dbo.PUBACC_SR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SR_uls_file_number ON dbo.PUBACC_SR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_SV
CREATE NONCLUSTERED INDEX IX_PUBACC_SV_unique_system_identifier ON dbo.PUBACC_SV
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_SV_uls_file_number ON dbo.PUBACC_SV
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_TA
CREATE NONCLUSTERED INDEX IX_PUBACC_TA_unique_system_identifier ON dbo.PUBACC_TA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_TA_uls_file_number ON dbo.PUBACC_TA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_TL
CREATE NONCLUSTERED INDEX IX_PUBACC_TL_unique_system_identifier ON dbo.PUBACC_TL
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_TL_uls_file_number ON dbo.PUBACC_TL
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_TP
CREATE NONCLUSTERED INDEX IX_PUBACC_TP_unique_system_identifier ON dbo.PUBACC_TP
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_TP_uls_file_number ON dbo.PUBACC_TP
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_UA
CREATE NONCLUSTERED INDEX IX_PUBACC_UA_unique_system_identifier ON dbo.PUBACC_UA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_UA_uls_file_number ON dbo.PUBACC_UA
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.PUBACC_VC
CREATE NONCLUSTERED INDEX IX_PUBACC_VC_unique_system_identifier ON dbo.PUBACC_VC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_PUBACC_VC_uls_file_number ON dbo.PUBACC_VC
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_AT
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_AT_unique_system_identifier ON dbo.TOWER_PUBACC_AT
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_CO
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_CO_unique_system_identifier ON dbo.TOWER_PUBACC_CO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_DE
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_DE_faa_study_number ON dbo.TOWER_PUBACC_DE
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_DP
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_DP_faa_study_number ON dbo.TOWER_PUBACC_DP
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_DR
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_DR_faa_study_number ON dbo.TOWER_PUBACC_DR
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_EN
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_EN_unique_system_identifier ON dbo.TOWER_PUBACC_EN
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_HS
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_HS_unique_system_identifier ON dbo.TOWER_PUBACC_HS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_RA
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_RA_unique_system_identifier ON dbo.TOWER_PUBACC_RA
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_RA_faa_study_number ON dbo.TOWER_PUBACC_RA
(
	[faa_study_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_RE
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_RE_unique_system_identifier ON dbo.TOWER_PUBACC_RE
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_RS
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_RS_unique_system_identifier ON dbo.TOWER_PUBACC_RS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.TOWER_PUBACC_SC
CREATE NONCLUSTERED INDEX IX_TOWER_PUBACC_SC_unique_system_identifier ON dbo.TOWER_PUBACC_SC
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_AN
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_AN_unique_system_identifier ON dbo.VACATED_PUBACC_AN
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_AN_uls_file_number ON dbo.VACATED_PUBACC_AN
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_EN
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_EN_unique_system_identifier ON dbo.VACATED_PUBACC_EN
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_EN_uls_file_number ON dbo.VACATED_PUBACC_EN
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_FR
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_FR_unique_system_identifier ON dbo.VACATED_PUBACC_FR
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_FR_uls_file_number ON dbo.VACATED_PUBACC_FR
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_HD
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_HD_unique_system_identifier ON dbo.VACATED_PUBACC_HD
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_HD_uls_file_number ON dbo.VACATED_PUBACC_HD
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_LO
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_LO_unique_system_identifier ON dbo.VACATED_PUBACC_LO
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_LO_uls_file_number ON dbo.VACATED_PUBACC_LO
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_MK
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_MK_unique_system_identifier ON dbo.VACATED_PUBACC_MK
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_MK_uls_file_number ON dbo.VACATED_PUBACC_MK
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

--dbo.VACATED_PUBACC_VS
CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_VS_unique_system_identifier ON dbo.VACATED_PUBACC_VS
(
	[unique_system_identifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

CREATE NONCLUSTERED INDEX IX_VACATED_PUBACC_VS_uls_file_number ON dbo.VACATED_PUBACC_VS
(
	[uls_file_number] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 50) ON [FCC_ULS_DatabaseIDX]
GO

use tempdb
GO
